Multiple removal of tastcases
akmohtashami/cms pull request #4
Opened 2017-03-26 04:53 UTC by kgolezardi

2017-03-26 06:33 UTC, akmohtashami requested changes

2017-03-26 06:33 UTC, akmohtashami commented on cms/server/admin/templates/task.html
> +          CMS.AWSUtils.ajax_delete('{{ url_root }}/dataset/{{ dataset.id }}/testcase/' + str + '/delete');
I think it's better to send the testcases as the data rather than in the URL. Like posting forms. 
The url scheme is a bit ugly this way.

2017-03-26 06:33 UTC, akmohtashami commented on cms/server/admin/templates/task.html
> +          console.log(str + " sent");
Don't forget your TODO :)

2017-03-27 08:35 UTC, akmohtashami approved these changes

2017-05-19 09:13 UTC, akmohtashami commented
Send this to the main repo.

2017-06-05 17:50 UTC, akmohtashami commented
1- Update this with recent changes 
2- Suggestion: don't track the selection and unselection of objects. instead iterate over all to see which one is selected when deleting. 
This resolves the following issue:
a- Select one or more testcases to delete
b- Press f5
c- Your browser keeps your selection so the expectation would be that when you click on delete testcases it will delete them but it will say no testcase is selected.

2017-07-17 21:29 UTC, kgolezardi commented
Not compatible with the recent changes of main repo. Will create another PR soon...

2017-07-17 21:29 UTC, closed without merging